// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKJ3UmGdHhsk7o5WjCUpipATowAC5N70',
    appId: '1:656869483:web:e195edae45cd8416b3092e',
    messagingSenderId: '656869483',
    projectId: 'edulink-5f65f',
    authDomain: 'edulink-5f65f.firebaseapp.com',
    storageBucket: 'edulink-5f65f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1k1BsQN-mOcu1yxKnrhlZjWryq7rtoZs',
    appId: '1:656869483:android:f79aef4cf05cdb2bb3092e',
    messagingSenderId: '656869483',
    projectId: 'edulink-5f65f',
    storageBucket: 'edulink-5f65f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOF2gWYOMjbFlgoBR89wOPLOoOhvpXzYU',
    appId: '1:656869483:ios:c2b698be40a95ba3b3092e',
    messagingSenderId: '656869483',
    projectId: 'edulink-5f65f',
    storageBucket: 'edulink-5f65f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOF2gWYOMjbFlgoBR89wOPLOoOhvpXzYU',
    appId: '1:656869483:ios:c2b698be40a95ba3b3092e',
    messagingSenderId: '656869483',
    projectId: 'edulink-5f65f',
    storageBucket: 'edulink-5f65f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzKJ3UmGdHhsk7o5WjCUpipATowAC5N70',
    appId: '1:656869483:web:40bb35c754a602fcb3092e',
    messagingSenderId: '656869483',
    projectId: 'edulink-5f65f',
    authDomain: 'edulink-5f65f.firebaseapp.com',
    storageBucket: 'edulink-5f65f.firebasestorage.app',
  );
}
